services:
  postgres:
    image: postgres:18
    container_name: mansour-accounting-db
    environment:
      POSTGRES_DB: mansour_accounting
      POSTGRES_USER: khalil
      POSTGRES_PASSWORD: khalil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: